services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olx_scraper
    depends_on:
      - db
    env_file: .env
    environment:
      - POSTGRES_URI=db
      - TZ=Europe/Kiev
    volumes:
      - .:/app
      - ./dumps:/app/dumps
    restart: always


  db:
    image: postgres:15
    container_name: postgres_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
